
services:
  postgres:
    image: postgres:17
    container_name: ecommerce_postgres_app
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      # Nơi Postgres lưu trữ dữ liệu
      - postgres_data:/var/lib/postgresql/data
        # Nơi chứa file init.sql để khởi tạo database (nếu có)
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql:ro


  redis:
    image: redis:7
    container_name: ecommerce_redis_app
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env

  app:
    image: error444/ecommerce-app:latest
    build: .
    container_name: ecommerce_app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # Redis
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATA_REDIS_DATABASE: ${REDIS_DATABASE}

      # Các biến khác (JWT, Cloudinary, Email, VNPay…)
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}

      TOKEN_EMAIL_VERIFICATION_EXPIRATION_MINUTES: ${TOKEN_EMAIL_VERIFICATION_EXPIRATION_MINUTES}
      TOKEN_REFRESH_EXPIRATION_DAYS: ${TOKEN_REFRESH_EXPIRATION_DAYS}

      # Cloudinary
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER}

      # Email
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_PROPERTIES_MAIL_SMTP_AUTH: ${EMAIL_PROPERTIES_MAIL_SMTP_AUTH}
      EMAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${EMAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

      # VNPay
      VNPAY_TMNCODE: ${VNPAY_TMNCODE}
      VNPAY_SECRET_KEY: ${VNPAY_SECRET_KEY}
      VNPAY_URL: ${VNPAY_URL}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL}
      VNPAY_VERSION: ${VNPAY_VERSION}
      VNPAY_COMMAND: ${VNPAY_COMMAND}
      VNPAY_CURRCODE: ${VNPAY_CURRCODE}
      VNPAY_ORDER_TYPE: ${VNPAY_ORDER_TYPE}

      # OTP & Login
      OTP_EXPIRATION_MINUTES: ${OTP_EXPIRATION_MINUTES}
      OTP_LENGTH: ${OTP_LENGTH}
      OTP_MAX_ATTEMPTS: ${OTP_MAX_ATTEMPTS}
      OTP_ATTEMPT_EXPIRY_MINUTES: ${OTP_ATTEMPT_EXPIRY_MINUTES}
      LOGIN_MAX_ATTEMPTS: ${LOGIN_MAX_ATTEMPTS}
      LOGIN_ATTEMPT_EXPIRY_MINUTES: ${LOGIN_ATTEMPT_EXPIRY_MINUTES}

volumes:
  postgres_data:
    name: ecommerce_postgres_data
